cursor_shape block

cursor_blink_interval 0
hide_window_decorations yes

font_family      family="Berkeley Mono"
font_size        13
bold_font        auto
italic_font      auto
bold_italic_font auto

include ~/.dotfiles/vim/plugged/tokyonight.nvim/extras/kitty/tokyonight_night.conf
set background=dark
# include ~/.dotfiles/vim/plugged/tokyonight.nvim/extras/kitty/tokyonight_day.conf
# set background=light
